version: '2'
services:
  webserver:
    image: <REPO>/microservices_webserver
    cpu_shares: 100
    mem_limit: 524288000
    ports:
      - "8000:8000"
    links:
      - processoring
      - information
  processor:
    image: <REPO>/microservices_processor
    cpu_shares: 100
    mem_limit: 524288000
    ports:
      - "8082"
  info:
    image: <REPO>/microservices_info
    cpu_shares: 100
    mem_limit: 524288000
    ports:
      - "8092"
